#Replicator properties
consumer:
   bootstrapAddress: ${CONSUMER_BOOTSTRAP_ADDRESS}
#SASL_PLAINTEXT
   security:
      protocol: ${CONSUMER_SECURITY_PROTOCOL}
# org.apache.kafka.common.security.plain.PlainLoginModule required username='${CONSUMER_USER}'   password='${CONSUMER_PASSWORD}';
   sasl:
      jaas:
         config: ${CONSUMER_JAAS_CONFIG}
# PLAIN
      mechanism: ${CONSUMER_SASL_MECHANISM}
# sbn.alarmlog-esp.bulk
   topic:
      names:
         ${CONSUMER_TOPIC_NAMES}
# java.replicator.generic
   group:
      id: ${CONSUMER_GROUP_ID}
# http://epi1moaireg01v:8081
   schema:
      registry: 
         url: ${CONSUMER_SCHEMA_REGISTRY_URL}

producer:
   bootstrapAddress: ${PRODUCER_BOOTSTRAP_ADDRESS}
# SASL_SSL
   security:
      protocol: ${PRODUCER_SECURITY_PROTOCOL}
# org.apache.kafka.common.security.scram.ScramLoginModule required username='${PRODUCER_USER}'   password='${PRODUCER_PASSWORD}';
   sasl:
      jaas: 
         config: ${PRODUCER_JAAS_CONFIG}
# SCRAM-SHA-512
      mechanism: ${PRODUCER_SASL_MECHANISM}
   #topic:
      #names: 
         #- ${PRODUCER_TOPIC_NAME}
# http://epi1regmoaii01v:8081
   schema: 
      registry:
         url: ${PRODUCER_SCHEMA_REGISTRY_URL}





